# Generated by Django 2.1.7 on 2019-04-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_stat', models.CharField(blank=True, choices=[('DAMAGED', 'DAMAGED'), ('IN USE', 'IN USE'), ('MISSING', 'MISSING'), ('TRANSFERRED', 'TRANSFERRED')], max_length=20, null=True)),
                ('pr_stat', models.CharField(blank=True, choices=[('DAMAGED', 'DAMAGED'), ('IN USE', 'IN USE'), ('MISSING', 'MISSING'), ('TRANSFERRED', 'TRANSFERRED')], max_length=20, null=True)),
                ('mm_stat', models.CharField(blank=True, choices=[('DAMAGED', 'DAMAGED'), ('IN USE', 'IN USE'), ('MISSING', 'MISSING'), ('TRANSFERRED', 'TRANSFERRED')], max_length=20, null=True)),
                ('mb_tran', models.CharField(blank=True, choices=[('REPAIR', 'REPAIR'), ('REPLACE', 'REPLACE'), ('RETURN', 'RETURN'), ('TRANSFER', 'TRANSFER')], max_length=20, null=True)),
                ('pr_tran', models.CharField(blank=True, choices=[('REPAIR', 'REPAIR'), ('REPLACE', 'REPLACE'), ('RETURN', 'RETURN'), ('TRANSFER', 'TRANSFER')], max_length=20, null=True)),
                ('mm_tran', models.CharField(blank=True, choices=[('REPAIR', 'REPAIR'), ('REPLACE', 'REPLACE'), ('RETURN', 'RETURN'), ('TRANSFER', 'TRANSFER')], max_length=20, null=True)),
                ('mb_war', models.DateField(blank=True, null=True)),
                ('pr_war', models.DateField(blank=True, null=True)),
                ('mm_war', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comp', models.CharField(max_length=30)),
                ('nm_dept', models.CharField(choices=[('Accounting', 'Accounting'), ('Laboratory', 'Laboratory')], max_length=50)),
                ('nm_loc', models.CharField(choices=[('Q.C', 'Q.C'), ('Manila', 'Manila')], max_length=50)),
                ('nm_supp', models.CharField(choices=[('PC EXPRESS', 'PC EXPRESS'), ('PCX', 'PCX')], max_length=50)),
                ('or_no', models.CharField(max_length=30)),
                ('date_req', models.DateTimeField()),
                ('date_pur', models.DateTimeField()),
                ('mb_brand', models.CharField(choices=[('ASROCK', 'ASROCK'), ('ASUS', 'ASUS'), ('BIOSTAR', 'BIOSTAR'), ('GIGABYTE', 'GIGABYTE'), ('MSI', 'MSI')], max_length=50)),
                ('mb_mod', models.CharField(max_length=50)),
                ('mb_specs', models.CharField(max_length=50)),
                ('mb_sr', models.CharField(max_length=50)),
                ('pr_brand', models.CharField(choices=[('AMD', 'AMD'), ('INTEL', 'INTEL')], max_length=50)),
                ('pr_mod', models.CharField(max_length=50)),
                ('pr_specs', models.CharField(max_length=50)),
                ('pr_sr', models.CharField(max_length=50)),
                ('mm_brand', models.CharField(choices=[('BINFUL', 'BINFUL'), ('KILLSRE', 'KILLSRE'), ('KINGSPEC', 'KINGSPEC'), ('KIGSTON', 'KIGSTON'), ('SAMSUNG', 'SAMSUNG')], max_length=50)),
                ('mm_mod', models.CharField(max_length=50)),
                ('mm_specs', models.CharField(max_length=50)),
                ('mm_sr', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='transac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticketing.Transaction'),
        ),
    ]
