# Generated by Django 2.1.7 on 2019-04-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_pur',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_req',
            field=models.DateField(),
        ),
    ]
