# Generated by Django 2.1.7 on 2019-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketing', '0002_auto_20190428_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mb_brand',
            field=models.CharField(blank=True, choices=[('ASROCK', 'ASROCK'), ('ASUS', 'ASUS'), ('BIOSTAR', 'BIOSTAR'), ('GIGABYTE', 'GIGABYTE'), ('MSI', 'MSI')], max_length=50, null=True),
        ),
    ]
