# Generated by Django 2.1.7 on 2019-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketing', '0004_auto_20190428_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_pur',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_req',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_comp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nm_dept',
            field=models.CharField(blank=True, choices=[('Accounting', 'Accounting'), ('Laboratory', 'Laboratory')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nm_loc',
            field=models.CharField(blank=True, choices=[('Q.C', 'Q.C'), ('Manila', 'Manila')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nm_supp',
            field=models.CharField(blank=True, choices=[('PC EXPRESS', 'PC EXPRESS'), ('PCX', 'PCX')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='or_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
